steps:
  - command: .buildkite/scripts/steps/artifacts/docker_image.sh
    label: 'Build Project Image'
    agents:
      machineType: c4d-standard-16
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
      diskSizeGb: 150
    timeout_in_minutes: 90
    soft_fail: true
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
