steps:
  - command: .buildkite/scripts/steps/cloud/build_and_deploy.sh
    label: 'Build and Deploy to Cloud'
    agents:
      machineType: c4d-standard-2
      diskType: hyperdisk-balanced
      preemptible: true
      spotZones: us-central1-c,us-central1-a
    depends_on:
      - build
      - quick_checks
      - checks
      - linting
      - linting_with_types
      - check_types
    timeout_in_minutes: 30
    soft_fail: true
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
